- become: true
  hosts: 127.0.0.1
  name: Run my CloudFormation stack
      cloudformation:
        stack_name:  "{{ lookup('env','RDS_STACK_NAME') }}"
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
        region: "{{ lookup('env','REGION') }}"
        state: "present"
        template_body: "{{ lookup('template', 'cloudformation.yaml.j2') }}"
        template_parameters:
          DBInstanceClass: "{{ lookup('env','DBINSTANCECLASS') }}"
          Engine: "{{ lookup('env','ENGINE') }}"
          MasterUsername: "{{ lookup('env','SQLSERVER_USERNAME') }}"
          MasterUserPassword: "{{ lookup('env','SQLSERVER_PASSWORD') }}"
          AllocatedStorage: "20"
          DBPortNumber: "{{ lookup('env','SQLSERVER_DBPORT') }}"
          DBInputCIDR: "{{ lookup('env','RDS_CIDR') }}"
          VPCSecurityGroups: "{{ lookup('env','RDS_SECURITYGROUPID') }}"
        on_create_failure: DELETE
